### Sign up a new user
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "email": "test2@gmail.com",
    "password": "1234"
}

### Sign in user
POST http://localhost:3000/api/auth/signin
content-type: application/json

{
    "email": "test2@gmail.com",
    "password": "1234"
}

### Get all Users by email
GET http://localhost:3000/api/auth/users?email=test@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImlhdCI6MTY4NTE3OTczOSwiZXhwIjoxNjg1MjY2MTM5fQ.g7Uh_7oqvPTZYAXnYKOzFCb5eQPE9zM_6XsfXgBa6IA

### Create a new product
POST http://localhost:3000/api/top-page
content-type: application/json

{
   "firstCategory": 1,
  "secondCategory": "Графический дизайн",
  "alias": "photoshop-alias",
  "title": "Photoshop",
  "category": "photoshop",
  "seoText": "Тест",
  "tagsTitle": "Заголвок",
  "advantages": [
    {
      "title": "1",
      "description": "Опсиание 1"
    }
  ],
  "tags": ["Learn photoshop"]
}